imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@IcUsuariosBundle/Resources/config/services.yml" }
    - { resource: "@IcFrontendBundle/Resources/config/services.yml" }
    - { resource: "@IcBackendBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: IcUsuariosBundle\Entity\User
    from_email:
        address: 'zuleyma.estrada@xolos.com.mx'
        sender_name: zuleyma estrada


#EasyAdmin Bundle
easy_admin:
    site_name: Xoloitzcuintles
    design:
        brand_color: '#c0392b'

    list:
        title: 'Lista de %%entity_label%%'

    entities:
        IcArea:
            class: IcBackendBundle\Entity\IcArea
            label: Area
            actions: - { name: 'edit', icon: 'pencil', label: 'Edit' }
        IcCategoria:
            class: IcBackendBundle\Entity\IcCategoria
            label: Categoria
        IcCentroTrabajo:
            class: IcBackendBundle\Entity\IcCentroTrabajo
            label: Centro de Trabajo
        IcDireccion:
            class: IcBackendBundle\Entity\IcDireccion
            label: Direccion
        IcGerencia:
            class: IcBackendBundle\Entity\IcGerencia
            label: Gerencia
        IcPuesto:
            class: IcBackendBundle\Entity\IcPuesto
            label: Puesto de Trabajo

        IcSubcategoria:
            class: IcBackendBundle\Entity\IcSubcategoria
            label: Subcategoria

        IcUsuario:
            class: IcBackendBundle\Entity\IcUsuario
            label: Usuario
